server: 
  port: 1001

spring: 
  application: 
    name: spring-cloud-gateway-route
  cloud: 
    gateway: 
      routes: 
        - predicates: 
            ##- Path=/test/**
            - Path=/hi/**
          filters: 
            - StripPrefix=1
          uri: "http://localhost:8001/hi"
          ##uri: "http://www.baidu.com"
          ##uri: "http://localhost:9001/test"